services:
  CampaignEntity:
    class: phpList\helper\CampaignEntity
  MailingListEntity:
    class: phpList\helper\MailingListEntity
  SubscriberEntity:
    class: phpList\helper\SubscriberEntity
  TemplateEntity:
    class: phpList\helper\TemplateEntity
  TemplateImageEntity:
    class: phpList\helper\TemplateImageEntity
  Logger:
    class: phpList\helper\Logger
  Util:
    class: phpList\helper\Util
    arguments: [@Config, @Logger, @Database]
  EmailAddress:
    class:  phpList\EmailAddress
    arguments: [@Config, %emailaddress.address%]
  Config:
    class: phpList\Config
    arguments: [%config.configfile%]
  Database:
    class:  phpList\helper\Database
    arguments: [@Config]
  Language:
    class: phpList\helper\Language
    arguments: [@Database, @Config]
  phpList:
    class: phpList\phpList
    arguments: [@Config, @Database, @Language, @Util]
  Campaign:
    class: phpList\Campaign
    arguments: [@Config, @Database, @MailingList, @Template]
  MailingList:
    class: phpList\MailingList
    arguments: [@Config, @Database]
  Subscriber:
    class: phpList\Subscriber
    arguments: [@Config, @Database]
  Template:
    class: phpList\Template
    arguments: [@Config, @Database, @TemplateImage]
  TemplateImage:
    class: phpList\TemplateImage
    arguments: [@Config, @Database]

# Define parameters, to be set in app logic
# NOTE: the classname.parameter syntax is just a Symfony convention; parameter
# names are handles as single simple strings
parameters:
  config.configfile: configfile
  emailaddress.address: emailaddress
  password.password: password
